"""
Anti-Corruption Layer (ACL) — The Fence

Translates between the legacy Spring Music Album shape and the Album Catalog
service's clean domain model. The fence is one-directional by design: legacy
shape enters, clean shape exits, and clean shape never leaks back out toward
the legacy monolith without translation.

Legacy shape:
{
  "id": "...",          # JPA primary key (numeric string or integer)
  "albumId": "...",     # 40-char random string — ghost field, dropped
  "title": "...",
  "artist": "...",
  "genre": "...",
  "releaseYear": "...", # dropped — not in new public model
  "trackCount": 0,      # camelCase — mapped to track_count
}

Clean shape (this service):
{
  "id": "...",          # UUID generated by this service
  "title": "...",
  "artist": "...",
  "genre": "...",
  "track_count": null,  # snake_case, optional
  "price": null         # optional
}

Rules enforced by this module:
  - albumId is always dropped on inbound translation (from_legacy)
  - trackCount (camelCase) is renamed to track_count on inbound translation
  - releaseYear and _class are always dropped on inbound translation
  - Clean responses never contain albumId, trackCount, _class, or releaseYear
    (enforced by validate_no_legacy_leak)
  - to_legacy_shape is provided only for the strangler-fig proxy scenario
    where the legacy client still expects the old shape
"""
from __future__ import annotations

from typing import Any, Dict

from models import Album, AlbumCreate

# Fields that must never appear in a clean-service response dict.
_LEGACY_FIELD_NAMES = frozenset({"albumId", "trackCount", "_class", "releaseYear"})


def from_legacy(legacy_dict: Dict[str, Any]) -> AlbumCreate:
    """
    Translate a legacy Spring Music Album payload into an AlbumCreate.

    Transformations applied:
      - ``albumId``     — dropped (ghost field, LB-3)
      - ``_class``      — dropped (Mongo type hint, not part of domain)
      - ``releaseYear`` — dropped (not part of new public model)
      - ``trackCount``  — renamed to ``track_count`` (camelCase -> snake_case)
      - ``id``          — dropped (legacy JPA key; the new service assigns UUIDs)
      - ``price``       — forwarded as-is if present

    Raises:
        ValueError: if ``title``, ``artist``, or ``genre`` are missing.
    """
    # Mandatory fields — let Pydantic raise the ValidationError if absent.
    title: str = legacy_dict["title"]
    artist: str = legacy_dict["artist"]
    genre: str = legacy_dict["genre"]

    # camelCase -> snake_case, treat 0 the same as "not set" (matches database.py logic)
    track_count_raw = legacy_dict.get("trackCount")
    track_count = track_count_raw if track_count_raw else None

    price = legacy_dict.get("price")

    return AlbumCreate(
        title=title,
        artist=artist,
        genre=genre,
        track_count=track_count,
        price=price,
    )


def to_legacy_shape(album: Album) -> Dict[str, Any]:
    """
    Translate a clean Album back to the legacy Spring Music shape.

    This is the reverse direction used exclusively by the strangler-fig proxy
    so that legacy consumers still receive the old wire format while traffic
    is being cut over.  The clean service itself never returns this shape.

    Transformations applied:
      - ``track_count`` -> ``trackCount`` (snake_case -> camelCase)
      - ``albumId``     — added as empty string (expected by legacy clients)
      - ``price``       — forwarded as-is
    """
    return {
        "id": album.id,
        "albumId": "",          # legacy ghost field — present but intentionally empty
        "title": album.title,
        "artist": album.artist,
        "genre": album.genre,
        "trackCount": album.track_count if album.track_count is not None else 0,
        "price": album.price,
    }


def validate_no_legacy_leak(album_dict: Dict[str, Any]) -> None:
    """
    Assert that a response dict from the clean service contains no legacy field names.

    Call this on any dict that is about to cross the boundary out of the clean
    service to verify that the anti-corruption layer has done its job.

    Raises:
        ValueError: listing every offending legacy field found in ``album_dict``.
    """
    offenders = _LEGACY_FIELD_NAMES & set(album_dict.keys())
    if offenders:
        raise ValueError(
            f"Legacy field(s) detected in clean service response — "
            f"ACL breach: {sorted(offenders)}"
        )
