from __future__ import annotations
from typing import Optional
from pydantic import BaseModel


class AlbumCreate(BaseModel):
    title: str
    artist: str
    genre: str
    track_count: Optional[int] = None
    price: Optional[float] = None


class Album(AlbumCreate):
    id: str  # UUID generated by the service

    model_config = {"from_attributes": True}


class AlbumUpdate(BaseModel):
    title: Optional[str] = None
    artist: Optional[str] = None
    genre: Optional[str] = None
    track_count: Optional[int] = None
    price: Optional[float] = None
